### ISSUE TITLE
cannot be loaded in 3.32

### ISSUE THREAD

**Issue by chama-chomo** [sunwxg/gnome-shell-extension-arrangeWindows#1]
`bře 22 14:44:07 brego-km gnome-shell[1427]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was pr>
bře 22 14:44:07 brego-km gnome-shell[1427]: JS WARNING: [/home/cqs/.local/share/gnome-shell/extensions/arrangeWindows@sun.wxg@gmail.com/extension.js 78]: reference to undefined property "_allMonitorToggle"
bře 22 14:44:07 brego-km gnome-shell[1427]: Extension "arrangeWindows@sun.wxg@gmail.com" had error: TypeError: this._allMonitorToggle is undefined
`

**Comment by sunwxg** [comment]
I updated. Could you give a try?

**Comment by chama-chomo** [comment]
Thx for the update, but I had to downgrade gnome, because too many extensions were failing. Will try later, or someone else maybe

**Comment by sunwxg** [comment]
I have tested on 3.32, it works now. Thanks!
