### ISSUE TITLE
Modifying the configuration using `gsettings`?

### ISSUE THREAD

**Issue by magthe** [sunwxg/gnome-shell-extension-arrangeWindows#11]
Would it be possible to put the configuration so it can be modified using `gsettings`/`dconf`?

It looks like there's a schema, and that it's at `org.gnome.shell.extensions.arrangeWindows` but Gnome doesn't seem to know anything about it:

```
❯ gsettings get org.gnome.shell.extensions.arrangeWindows all-monitors
No such schema “org.gnome.shell.extensions.arrangeWindows”
```

**Comment by sunwxg** [comment]
```
gsettings --schemadir ~/.local/share/gnome-shell/extensions/arrangeWindows@sun.wxg@gmail.com/schemas/ get org.gnome.shell.extensions.arrangeWindows all-monitors
```

**Comment by magthe** [comment]
Thanks, that works. Wouldn't it be even nicer if the schema was installed so it doesn't require the `--schemadir`? (I have several other extensions that does that and it's very handy for extensions without a full configuration GUI.)

**Comment by sunwxg** [comment]
Sorry, I don't know how to do it like you said.

**Comment by magthe** [comment]
Neither do I :relaxed:  I don't know how to write Gnome Shell plugins at all!

Here's one plugin that does registers its config in a way so `--schemadir` isn't necessary: https://github.com/GSConnect/gnome-shell-extension-gsconnect

Maybe it's possible to figure out how it's done from that. If you are interested at all that is :smiley: 

Anyway, I'm closing this ticket as the command line you gave me above does work (I needed to change the key combinations as they conflicted with  others I have already).

Thanks for your help, and thanks for a nice plugin.
