### ISSUE TITLE
Use spin buttons instead of slider to set the number of tiles

### ISSUE THREAD

**Issue by andreastedile** [sunwxg/gnome-shell-extension-arrangeWindows#13]
First of all, thank you for this flawless extension!

Although I think that GTK elements can't be used directly in shell extensions, I think something like this would look and function better than the current slider implementation: https://docs.gtk.org/gtk4/class.SpinButton.html

**Comment by sunwxg** [comment]
gnome-shell doesn't use GTK component, all the components like slider in gnome-shell are designed by itself above clutter, and it is written by C code and used by JS. For an extension it's almost impossible to write a new component to use.

**Comment by andreastedile** [comment]
Exactly. Looking in the repository, it does not seem that clutter provides spin buttons right now https://gitlab.gnome.org/GNOME/gnome-shell/-/tree/main/js/ui
