### ISSUE TITLE
Tiling Multi-Monitor 

### ISSUE THREAD

**Issue by ktonekaboni** [sunwxg/gnome-shell-extension-arrangeWindows#3]
Hi, 

I have two monitors and like to use your great extension on both monitors separately. I use this plugin to control both monitors separately: https://extensions.gnome.org/extension/921/multi-monitors-add-on/
A workaround for me is to "fork" your extension, to have it twice. One for each display. That works.

I'm not sure, how it could be down from UI and without to build a dependency with another extension. For example: Single Monitor, All Monitors, On Monitor with focus*

*monitor of the last focussed window.

**Comment by sunwxg** [comment]
I need to add another option 'On Focused Monitor' except 'Single Monitor' and 'All Monitors'.

**Comment by sunwxg** [comment]
commit 7abf5ee373107dde083614a7cb28eda1bc33c6ee solved.
